<?php 
$title = "Articles";
$nav = "articles";
require 'elements/header.php'; ?>

<div class="main-conteneur">

    <div class="container clearfix">

        <div id="et-main-area">
        
            <div id="main-content">

                <article id="post-878" class="post-878 page type-page status-publish hentry">
                    <div class="entry-content">
                        <div class="et-l et-l--post">
                            <div class="et_builder_inner_content et_pb_gutters3"><div class="et_pb_section et_pb_section_0 et_section_regular">
                                <div class="et_pb_row et_pb_row_0">
                                    <div class="et_pb_column et_pb_column_4_4 et_pb_column_0  et_pb_css_mix_blend_mode_passthrough et-last-child">
                                        <div class="et_pb_module et_pb_text et_pb_text_0  et_pb_text_align_left et_pb_bg_layout_light">
                                            <div class="et_pb_text_inner"><h1>Mentions légales</h1></div>
                                        </div>
                                        <div class="et_pb_module et_pb_text et_pb_text_1  et_pb_text_align_left et_pb_bg_layout_light">
                                            <div class="et_pb_text_inner">

                                                <h2>Définitions</h2>
                                                    <p><b>Client :</b><span style="font-weight: 400;"> tout professionnel ou personne physique capable au sens des articles 1123 et suivants du Code civil, ou personne morale, qui visite le Site objet des présentes conditions générales.</span></p>
                                                    <p><b>Prestations et Services :</b><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;"> met à disposition des Clients :</span></p>
                                                    <p><b>Contenu :</b><span style="font-weight: 400;"> Ensemble des éléments constituants l’information présente sur le Site, notamment textes – images – vidéos.</span></p>
                                                    <p><b>Informations clients :</b><span style="font-weight: 400;"> Ci après dénommé « Information (s) » qui correspondent à l’ensemble des données personnelles susceptibles d’être détenues par</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;"> pour la gestion de votre compte, de la gestion de la relation client et à des fins d’analyses et de statistiques.</span></p>
                                                    <p><b>Utilisateur :</b><span style="font-weight: 400;"> Internaute se connectant, utilisant le site susnommé.</span></p>
                                                    <p><b>Informations personnelles :</b><span style="font-weight: 400;"> « Les informations qui permettent, sous quelque forme que ce soit, directement ou non, l’identification des personnes physiques auxquelles elles s’appliquent » (article 4 de la loi n° 78-17 du 6 janvier 1978).</span></p>
                                                    <p><span style="font-weight: 400;">Les termes « données à caractère personnel », « personne concernée », « sous traitant » et « données sensibles » ont le sens défini par le Règlement Général sur la Protection des Données (RGPD : n° 2016-679)</span></p>
                                                
                                                <h2>1. Présentation du site internet.</h2>
                                                    <p><span style="font-weight: 400;">En vertu de l’article 6 de la loi n° 2004-575 du 21 juin 2004 pour la confiance dans l’économie numérique, il est précisé aux utilisateurs du site internet</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;"> l’identité des différents intervenants dans le cadre de sa réalisation et de son suivi:</span></p>
                                                    <p><b>Propriétaire</b><span style="font-weight: 400;"> : Amélie BRIAND</span></p>
                                                    <p><b>Responsable publication</b><span style="font-weight: 400;"> : Amélie BRIAND – mail@amelie-briand.fr</span></p>
                                                    <p><span style="font-weight: 400;">Le responsable publication est une personne physique ou une personne morale.</span></p>
                                                    <p><b>Webmaster: </b>Aurélie COUDERT</p>
                                                    <p><b>Hébergeur</b><span style="font-weight: 400;"> : OVH – 2 rue Kellermann 59100 Roubaix 1007</span></p>
                                                    <p><b>Délégué à la protection des données</b><span style="font-weight: 400;"> : BRIAND Amélie mail@amelie-briand.fr</span></p>

                                                <h2>2. Conditions générales d’utilisation du site et des services proposés.</h2>
                                                    <p><span style="font-weight: 400;">Le Site constitue une œuvre de l’esprit protégée par les dispositions du Code de la Propriété Intellectuelle et des Réglementations Internationales applicables.</span></p>
                                                    <p><span style="font-weight: 400;">Le Client ne peut en aucune manière réutiliser, céder ou exploiter pour son propre compte tout ou partie des éléments ou travaux du Site.</span></p>
                                                    <p><span style="font-weight: 400;">L’utilisation du site</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;"> implique l’acceptation pleine et entière des conditions générales d’utilisation ci-après décrites. Ces conditions d’utilisation sont susceptibles d’être modifiées ou complétées à tout moment, les utilisateurs du site</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;"> sont donc invités à les consulter de manière régulière.</span></p>

                                                <h2>3. Description des services fournis.</h2>
                                                    <p><span style="font-weight: 400;">Le site internet</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;"> a pour objet de fournir une information concernant l’ensemble des activités de la société.</span></p>
                                                    <p><a href="https://amelie-briand.fr"><span style="font-weight: 400;">https://amelie-briand.fr</span></a><span style="font-weight: 400;"> s’efforce de fournir sur le site</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;"> des informations aussi précises que possible. Toutefois, il ne pourra être tenu responsable des oublis, des inexactitudes et des carences dans la mise à jour, qu’elles soient de son fait ou du fait des tiers partenaires qui lui fournissent ces informations.</span></p>
                                                    <p><span style="font-weight: 400;">Toutes les informations indiquées sur le site</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;"> sont données à titre indicatif, et sont susceptibles d’évoluer. Par ailleurs, les renseignements figurant sur le site</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;"> ne sont pas exhaustifs. Ils sont donnés sous réserve de modifications ayant été apportées depuis leur mise en ligne.</span></p>

                                                <h2>4. Limitations contractuelles sur les données techniques.</h2>
                                                    <p><span style="font-weight: 400;">Le site utilise la technologie JavaScript.</span></p>
                                                    <p><span style="font-weight: 400;">Le site</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;"> est hébergé chez un prestataire sur le territoire de l’Union Européenne conformément aux dispositions du Règlement Général sur la Protection des Données (RGPD : n° 2016-679)</span></p>

                                                <h2>5. Propriété intellectuelle et contrefaçons.</h2>
                                                    <p><a href="https://amelie-briand.fr"><span style="font-weight: 400;">https://amelie-briand.fr</span></a><span style="font-weight: 400;"> est propriétaire des droits de propriété intellectuelle et détient les droits d’usage sur tous les éléments accessibles sur le site internet, notamment les textes, images, graphismes, logos, vidéos, icônes et sons.</span></p>
                                                    <p><span style="font-weight: 400;">Toute reproduction, représentation, modification, publication, adaptation de tout ou partie des éléments du site, quel que soit le moyen ou le procédé utilisé, est interdite, sauf autorisation écrite préalable de :</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;">.</span></p>
                                                    <p><span style="font-weight: 400;">Toute exploitation non autorisée du site ou de l’un quelconque des éléments qu’il contient sera considérée comme constitutive d’une contrefaçon et poursuivie conformément aux dispositions des articles L.335-2 et suivants du Code de Propriété Intellectuelle.</span></p>

                                                <h2>6. Limitations de responsabilité.</h2>
                                                    <p><a href="https://amelie-briand.fr"><span style="font-weight: 400;">https://amelie-briand.fr</span></a><span style="font-weight: 400;"> agit en tant qu’éditeur du site.</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;">&nbsp; est responsable de la qualité et de la véracité du Contenu qu’il publie.</span></p>
                                                    <p><span style="font-weight: 400;">Des espaces interactifs (possibilité de poser des questions dans l’espace contact) sont à la disposition des utilisateurs.</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;"> se réserve le droit de supprimer, sans mise en demeure préalable, tout contenu déposé dans cet espace qui contreviendrait à la législation applicable en France, en particulier aux dispositions relatives à la protection des données. Le cas échéant,</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;"> se réserve également la possibilité de mettre en cause la responsabilité civile et/ou pénale de l’utilisateur, notamment en cas de message à caractère raciste, injurieux, diffamant, ou pornographique, quel que soit le support utilisé (texte, photographie …).</span></p>

                                                <h2>7. Gestion des données personnelles.</h2>
                                                    <p><span style="font-weight: 400;">Se référer à la page</span><a href="https://amelie-briand.fr/politique-de-confidentialite"><span style="font-weight: 400;"> Politique de confidentialité</span></a></p>

                                                <h2>8. Liens hypertextes « cookies » et balises (“tags”) internet</h2>
                                                    <p><span style="font-weight: 400;">Le site</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;"> contient un certain nombre de liens hypertextes vers d’autres sites, mis en place avec l’autorisation de</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;">. Cependant,</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;"> n’a pas la possibilité de vérifier le contenu des sites ainsi visités, et n’assumera en conséquence aucune responsabilité de ce fait.</span></p>
                                                    <p><span style="font-weight: 400;">Sauf si vous décidez de désactiver les cookies, vous acceptez que le site puisse les utiliser. Vous pouvez à tout moment désactiver ces cookies et ce gratuitement à partir des possibilités de désactivation qui vous sont offertes et rappelées ci-après, sachant que cela peut réduire ou empêcher l’accessibilité à tout ou partie des Services proposés par le site.</span></p>

                                                <h3>8.1. « COOKIES »</h3>
                                                    <p><span style="font-weight: 400;">Un « cookie » est un petit fichier d’information envoyé sur le navigateur de l’Utilisateur et enregistré au sein du terminal de l’Utilisateur (ex : ordinateur, smartphone), (ci-après « Cookies »). Ce fichier comprend des informations telles que le nom de domaine de l’Utilisateur, le fournisseur d’accès Internet de l’Utilisateur, le système d’exploitation de l’Utilisateur, ainsi que la date et l’heure d’accès. Les Cookies ne risquent en aucun cas d’endommager le terminal de l’Utilisateur.</span></p>
                                                    <p><a href="https://amelie-briand.fr"><span style="font-weight: 400;">https://amelie-briand.fr</span></a><span style="font-weight: 400;"> est susceptible de traiter les informations de l’Utilisateur concernant sa visite du Site, telles que les pages consultées, les recherches effectuées. Ces informations permettent à</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;"> d’améliorer le contenu du Site, de la navigation de l’Utilisateur.</span></p>
                                                    <p><span style="font-weight: 400;">Les Cookies facilitant la navigation et/ou la fourniture des services proposés par le Site, l’Utilisateur peut configurer son navigateur pour qu’il lui permette de décider s’il souhaite ou non les accepter de manière à ce que des Cookies soient enregistrés dans le terminal ou, au contraire, qu’ils soient rejetés, soit systématiquement, soit selon leur émetteur. L’Utilisateur peut également configurer son logiciel de navigation de manière à ce que l’acceptation ou le refus des Cookies lui soient proposés ponctuellement, avant qu’un Cookie soit susceptible d’être enregistré dans son terminal.</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;"> informe l’Utilisateur que, dans ce cas, il se peut que les fonctionnalités de son logiciel de navigation ne soient pas toutes disponibles.</span></p>
                                                    <p><span style="font-weight: 400;">Si l’Utilisateur refuse l’enregistrement de Cookies dans son terminal ou son navigateur, ou si l’Utilisateur supprime ceux qui y sont enregistrés, l’Utilisateur est informé que sa navigation et son expérience sur le Site peuvent être limitées. Cela pourrait également être le cas lorsque</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;"> ou l’un de ses prestataires ne peut pas reconnaître, à des fins de compatibilité technique, le type de navigateur utilisé par le terminal, les paramètres de langue et d’affichage ou le pays depuis lequel le terminal semble connecté à Internet.</span></p>
                                                    <p><span style="font-weight: 400;">Le cas échéant,</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;"> décline toute responsabilité pour les conséquences liées au fonctionnement dégradé du Site et des services éventuellement proposés par</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;">, résultant (i) du refus de Cookies par l’Utilisateur (ii) de l’impossibilité pour</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;"> d’enregistrer ou de consulter les Cookies nécessaires à leur fonctionnement du fait du choix de l’Utilisateur. Pour la gestion des Cookies et des choix de l’Utilisateur, la configuration de chaque navigateur est différente. Elle est décrite dans le menu d’aide du navigateur, qui permettra de savoir de quelle manière l’Utilisateur peut modifier ses souhaits en matière de Cookies.</span></p>
                                                    <p><span style="font-weight: 400;">À tout moment, l’Utilisateur peut faire le choix d’exprimer et de modifier ses souhaits en matière de Cookies.</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;"> pourra en outre faire appel aux services de prestataires externes pour l’aider à recueillir et traiter les informations décrites dans cette section.</span></p>
                                                    <p><span style="font-weight: 400;">Enfin, en cliquant sur les icônes dédiées aux réseaux sociaux Twitter, Facebook, Linkedin et Google Plus figurant sur le Site de</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;"> ou dans son application mobile et si l’Utilisateur a accepté le dépôt de cookies en poursuivant sa navigation sur le Site Internet ou l’application mobile de</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;">, Twitter, Facebook, Linkedin et Google Plus peuvent également déposer des cookies sur vos terminaux (ordinateur, tablette, téléphone portable).</span></p>
                                                    <p><span style="font-weight: 400;">Ces types de cookies ne sont déposés sur vos terminaux qu’à condition que vous y consentiez, en continuant votre navigation sur le Site Internet ou l’application mobile de</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;">. À tout moment, l’Utilisateur peut néanmoins revenir sur son consentement à ce que</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;"> dépose ce type de cookies.</span></p>

                                                <h3>Article 8.2. BALISES (“TAGS”) INTERNET</h3>
                                                    <p><a href="https://amelie-briand.fr"><span style="font-weight: 400;">https://amelie-briand.fr</span></a><span style="font-weight: 400;"> peut employer occasionnellement des balises Internet (également appelées « tags », ou balises d’action, GIF à un pixel, GIF transparents, GIF invisibles et GIF un à un) et les déployer par l’intermédiaire d’un partenaire spécialiste d’analyses Web susceptible de se trouver (et donc de stocker les informations correspondantes, y compris l’adresse IP de l’Utilisateur) dans un pays étranger.</span></p>
                                                    <p><span style="font-weight: 400;">Ces balises sont placées à la fois dans les publicités en ligne permettant aux internautes d’accéder au Site, et sur les différentes pages de celui-ci.</span></p>
                                                    <p><span style="font-weight: 400;">Cette technologie permet à</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;"> d’évaluer les réponses des visiteurs face au Site et l’efficacité de ses actions (par exemple, le nombre de fois où une page est ouverte et les informations consultées), ainsi que l’utilisation de ce Site par l’Utilisateur.</span></p>
                                                    <p><span style="font-weight: 400;">Le prestataire externe pourra éventuellement recueillir des informations sur les visiteurs du Site et d’autres sites Internet grâce à ces balises, constituer des rapports sur l’activité du Site à l’attention de</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;">, et fournir d’autres services relatifs à l’utilisation de celui-ci et d’Internet.</span></p>

                                                <h2>9. Droit applicable et attribution de juridiction.</h2>
                                                    <p><span style="font-weight: 400;">Tout litige en relation avec l’utilisation du site</span><a href="https://amelie-briand.fr"><span style="font-weight: 400;"> https://amelie-briand.fr</span></a><span style="font-weight: 400;"> est soumis au droit français.</span></p>
                                                    <p><span style="font-weight: 400;">En dehors des cas où la loi ne le permet pas, il est fait attribution exclusive de juridiction aux tribunaux compétents de La Roche sur Yon</span></p>

                                                <h2>10. Code de la consommation.</h2>
                                                    <p>Conformément aux articles L.616-1 et R.616-1 du code de la consommation, nous proposons un dispositif de médiation de la consommation. L’entité de médiation retenue est : CNPM – MEDIATION DE LA CONSOMMATION. En cas de litige, vous pouvez déposer votre réclamation sur son site : https://cnpm-mediation-consommation.eu ou par voie postale en écrivant à CNPM – MEDIATION – CONSOMMATION – 27 avenue de la libération – 42400 Saint-Chamond</p></div>
                
                                            </div>
                                        </div>
                                    </div>
                                </div>		
                            </div>
                        </div>
                    </div>
                </article>
            </div>
        </div>
    </div>
</div>

<?php require 'elements/footer.php'; ?> 